### ISSUE TITLE
Can XBOX 360 version support more cores?

### ISSUE THREAD

**Issue by 25minutes** [revvv/RetroArchWiiRetrode#3]
RetroArchWiiRetrode-0.5 works with Xbox 360 controller properly. However, there are only 3 cores available.

RetroArch-1.7.8 has more cores but it results black screen. I have to press power button to shutdown Wii. From the readme, it appears this one doesn't support Xbox 360 controller.

Is it possible for XBOX 360 version support more cores?

**Comment by revvv** [comment]
To get more cores to work with XBOX 360 controller you have to compile them.

> RetroArch-1.7.8 has more cores but it results black screen. I have to press power button to shutdown Wii. From the readme, it appears this one doesn't support Xbox 360 controller.

Don't know why it does not run on your machine, but it does not support XBOX 360 controller. You could use official RA build. Right now you need a nightly build or wait for next official release 1.16.1, because USB was broken again.

**Comment by 25minutes** [comment]
Thanks for the reply. If possible, it will be great to get future updates for Xbox 360 version when you are convenient, as not many people have that skill level to compile.
